### PR TITLE
💚 Use babel-eslint in conjunction to flow

### PR DESCRIPTION
**Pull request by thibmaek**
The build task would fail since it lints before testing. Eslint would error since it would not recognize the type annotations declared in flow-checked files. Switched to using babel-eslint as the parser and the flowtype plugin. This is not opinionated but actually required in the current scenario.

### CODE REVIEW

**Comment by duivvv** [comment]
Have a couple of projects with linting + flow, no problems here? + Babel-eslint is loaded via the devine config..

Can you show me what happens in detail?

**Comment by duivvv** [comment]
I think you forgot "transform-flow-strip-types" in your bpost project, no? :)

**Comment by duivvv** [comment]
what is your global eslint version? (it uses it in the editor, could that cause the problem?)

https://github.com/duivvv/validate-note flow typing works fine here, or is this in a specific case?

**Comment by thibmaek** [comment]
Hmmm seemed to fail on me yesterday. Let me quickly recreate in temp folder and post back here in a couple of mins.

**Comment by thibmaek** [comment]
Ah yes I see it now (bit stupid not to look into it further). I only set stripping types in my cjs and es envs and not as a global babel plugin. Nevermind would indeed work stripping types out before linting (which is why jest also failed on me probably 😄 )

**Comment by thibmaek** [comment]
Also sidenote: you can use eslint in the editor without installing it globally ;)

**Comment by duivvv** [comment]
I know :) and everybody should

**Pull request closed without merging**
